spring:
  application:
    name: twitter-feign-client
server:
  port: ${PORT:8765}
eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}